"""empty message

Revision ID: 1a41d353c9f1
Revises: 
Create Date: 2022-05-28 20:13:24.262786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a41d353c9f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'nationalsociety', ['ns_id'], ['ns_go_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'nationalsociety', ['ns_id'], ['id'])
    # ### end Alembic commands ###
