"""empty message

Revision ID: f03f94533a51
Revises: 
Create Date: 2022-06-01 13:25:12.051012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03f94533a51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_language', sa.Column('language_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'user_language', type_='foreignkey')
    op.create_foreign_key(None, 'user_language', 'language', ['language_id'], ['id'])
    op.drop_column('user_language', 'skill_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_language', sa.Column('skill_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'user_language', type_='foreignkey')
    op.create_foreign_key(None, 'user_language', 'language', ['skill_id'], ['id'])
    op.drop_column('user_language', 'language_id')
    # ### end Alembic commands ###
